cms_home:
    path:  /admin/
    defaults: { _controller: DashboardManagerBundle:Dashboard:index }
cms_home2:
    path:  /admin/dashboard
    defaults: { _controller: DashboardManagerBundle:Dashboard:index }

