parameters:
#    dashboard_manager.example.class: Oni\DashboardManagerBundle\Example

services:
#    dashboard_manager.example:
#        class: %dashboard_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
